version: '3.8'

services:

  database:
    image: postgres
    container_name: postgres-container-payment-service
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
